name: 📃 Documentation Request
description: Suggest what wrong!
title: "📃 Feature Request: "
labels: 
  - Documentation

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Documentation Request report.
  - type: textarea
    attributes:
      label: Please describe your documentation request related to a problem?
      description: 'A one-liner title for the feature.'
  - type: textarea
    attributes:
      label: Additional context
      description: 'Add any other context or screenshots about the feature request here.'
  - type: textarea
    attributes:
      label: Add Relevant Screenshot (if available)
      description: 'supporting an issue'
